# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ensight Enterprises, LLC
email: jason@ensightenterprises.com
description: > # this means to ignore newlines until "baseurl:"
  Ensight Enterprises provides businesses with software consulting services
  including custom application development, product management, and project
  mangement. We primarily serve startup and early stage companies who need
  technical guidance to execute on their vision and get their product to market.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ensightenterprises.com" # the base hostname & protocol
twitter_username: iamenspired
# github_username:  jcartwright
# github:
#   owner_name: "Jason Cartwright"
#   owner_url: "https://github.com/jcartwright"

# Build settings
markdown: kramdown
# theme: jekyll-theme-slate
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
